# -*- mode: ruby -*-
# vi: set ft=ruby :

$post_script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
CHK_USER=`grep operation /etc/passwd`
if [[ -z $CHK_USER ]]; then
useradd -d /data operation
mkdir -p ~operation/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjggePUaVLZxoUcvaAixJBPmRLpMIHW/4YQ8eerUFUW98WYvev1iEeu2t7C7XtTdotzVnlK/SvfCArxlf5XsOYctKQ/pwA1ehrrXAMZNNuQmOVvKgNney38VojA1g4/iUTn/1iVg84cuo/1i44qrgkjo815FPfNy+L63Z4Z9+wSPe70Bm5rV8r/55uJ/RbYhFRCIFjpcyztcjcyNWNJ0KJk8AvlOuRCRSqQnzkCxvs+4uNgoly5+zqZs8ewOWXB/I7rlOeGjX26WC90rh6JlsuVdbW9B51AFqS7FOFG1NVZYfE3e6SF9JM+AkFgsdLRgpzXpxL5RpRrX6eL7FP4NPh operation@jenkins" > ~operation/.ssh/authorized_keys
fi
echo "operation     ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
chown -R operation.operation /data
ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
SCRIPT

Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/vagrant"
  end
  config.vm.define "kubeadmin" do |kubeadmin|
    kubeadmin.vm.box = "ubuntu/xenial64"
    kubeadmin.vm.hostname = "kubeadmin"
    #kubeadmin.vm.network "forwarded_port", guest: 8080, host: 8080
    kubeadmin.vm.network "private_network", ip: "10.200.200.51"
    kubeadmin.vm.provision "shell", inline: $post_script
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--memory", "4096"]
    end
  end

  config.vm.define "kubenode01" do |kubenode01|
    kubenode01.vm.box = "ubuntu/xenial64"
    kubenode01.vm.hostname = "kubenode01"
    #kubenode01.vm.network "forwarded_port", guest: 8080, host: 8080
    kubenode01.vm.network "private_network", ip: "10.200.200.52"
    kubenode01.vm.provision "shell", inline: $post_script
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define "kubenode02" do |kubenode02|
    kubenode02.vm.box = "ubuntu/xenial64"
    kubenode02.vm.hostname = "kubenode02"
    #kubenode02.vm.network "forwarded_port", guest: 8080, host: 8080
    kubenode02.vm.network "private_network", ip: "10.200.200.53"
    kubenode02.vm.provision "shell", inline: $post_script
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define "kubenode03" do |kubenode03|
    kubenode03.vm.box = "ubuntu/xenial64"
    kubenode03.vm.hostname = "kubenode03"
    #kubenode03.vm.network "forwarded_port", guest: 8080, host: 8080
    kubenode03.vm.network "private_network", ip: "10.200.200.54"
    kubenode03.vm.provision "shell", inline: $post_script
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
end